# Generated by Django 3.0.3 on 2020-03-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0004_auto_20200229_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='camp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('venue', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=500)),
                ('img', models.ImageField(upload_to='pictures')),
            ],
        ),
    ]
