# Generated by Django 3.0.3 on 2020-03-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0005_camp'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='boo',
            field=models.BooleanField(default=False),
        ),
    ]
