# Generated by Django 3.0.3 on 2020-03-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0007_auto_20200306_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='usname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
