# Generated by Django 3.0.3 on 2020-03-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0008_profile_usname'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='camp',
            name='month',
            field=models.CharField(default='', max_length=10),
        ),
    ]
