# Generated by Django 3.0.3 on 2020-03-09 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0009_auto_20200309_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='month',
            field=models.CharField(default='', max_length=10),
        ),
    ]
