# Generated by Django 3.0.3 on 2020-03-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0011_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='videofile',
            new_name='imagefile',
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(default='', max_length=500),
        ),
    ]
