# Generated by Django 3.0.3 on 2020-03-14 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0012_auto_20200314_1438'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
