# Generated by Django 3.0.3 on 2020-03-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub', '0014_auto_20200325_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopt',
            name='doc',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='mes',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='adopt',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
